### PR TITLE
fix: input property fingerprinting

### PR DESCRIPTION
**Pull request by nbrugger-tgm**
replace a "hardcoded/real" property with a gradle style one so gradle can actually use the input as such

Closes: #120

### CODE REVIEW

**Comment by nbrugger-tgm** [comment]
@stevesaliman

**Comment by nbrugger-tgm** [comment]
@MalloD12

**Comment by stevesaliman** [comment]
The next release of the plugin is going to use the Liquibase Command API instead of a JavaExec, so this PR may not be needed anymore.

I'm just waiting on a fix in Liquibase, which will hopefully be in the next LB release.

**Comment by kevin-atx** [comment]
@stevesaliman  - the command API fix will be released with Liquibase 4.28.0 on 5/21/2024 (today). Starting with this release, you should be able to re-implement the Gradle plugin to take advantage of the command API.

**Comment by kevin-atx** [comment]
@stevesaliman - were you able to test with the 4.28.0 release of Liquibase to see if this PR is still needed?

**Comment by stevesaliman** [comment]
Unfortunately, version 4.28.0 still has an issue with changelog parameters and teh Command API, so I can't finish my testing.

**Comment by MalloD12** [comment]
Hey @stevesaliman, could you please point us to the changelog parameters issue you are seeing? 

Thanks,
Daniel.

**Comment by stevesaliman** [comment]
The issue is in how the Gradle plugin interacts with the new CommandScope API.  When a task executes, it creates a new ChangelogParameters object to store any parameters given to it by Gradle before calling CommandScope.execute.  Since there is no database connection at this point, the database is null, so the database filters are also null.

I set a breakpoint in the ChangeLogParameters constructor and in Liquibase 4.20.0, the constructor would be called by the Gradle plugin before calling execute, but it would be called again after calling execute, this time with a database.  The Groovy DSL's parse method would then be given parameters with all the parameters and databaseFilters.

But in 4.21.0, the constructor is only called once, and the the parameters made by the plugin are the parameters given to the parse method.  Since the database is null, it isn't properly handling ChangeLogParameters that had the `dbms` attribute set.

I'm not sure what changed from 4.20 to 4.21, but something change that gets in the way of the changelog parameters working, and I haven't figured out how to work around it yet.

**Comment by stevesaliman** [comment]
The next version of the plugin will not be able to use the command API, because the changelog parameter issue remains.  So LiquibaseTasks will continue to be JavaExec tasks, and your fix will likely need to be implemented in the new code.

I pushed the `cli-api` branch with the new code if you want to take a look.  It shouldn't be too hard to make the required changes to that branch before it gets released.

**Comment by stevesaliman** [comment]
The LiquibaseCommand class is no longer part of the plugin, as of version 4.0.0, so this PR is no longer needed.

**Pull request closed without merging**
