### PR TITLE
add --integration-name parameter to all commands executed through gradle (DAT-18607) 

### PR DESCRIPTION
**Pull request by StevenMassaro**

### CODE REVIEW

**Comment by stevesaliman** [comment]
I just noticed this PR.  I'm concerned about backwards compatibility, as `--liquibase-interface` doesn't apper to be a valid global configuration argument.

Is this a new argument that will be added to a furute release of Liquibase?

**Comment by StevenMassaro** [comment]
> I just noticed this PR. I'm concerned about backwards compatibility, as `--liquibase-interface` doesn't apper to be a valid global configuration argument.
> 
> Is this a new argument that will be added to a furute release of Liquibase?

Yes. I'm exploring the option of only adding this parameter if the version of Liquibase is detected as being compatible (recent enough) with the parameter. How does that sound?

**Comment by stevesaliman** [comment]
Good thing I didn't pull the version provider - I had been considering it...

Out of curiosity, could  you achieve the same functionality by checking if the  allGlobalArguments map contains `integrationName`?  That way there would be no work to do if the integrationName argument ever went away.

**Comment by StevenMassaro** [comment]
> Out of curiosity, could you achieve the same functionality by checking if the allGlobalArguments map contains `integrationName`? That way there would be no work to do if the integrationName argument ever went away.

I think this should work, it would also make it a lot easier to manage releasing this extension and Liquibase itself. I will try it out, thanks for the idea!

**Review by stevesaliman — APPROVED** [review]

**Pull request merged**
