### PR TITLE
[fix] gradle 6.4 incompatibility

### LINKED ISSUE #70: Gradle 6.4 problems
Upgrading gradle to 6.4 causes build problems.

```
> Task :liquibaseUpdate FAILED                                                                                                                                                                                                                                
Caching disabled for task ':liquibaseUpdate' because:                                                                                                                                                                                                         
  Build cache is disabled                                                                                                      
Task ':liquibaseUpdate' is not up-to-date because:                                                                             
  Task has not declared any outputs despite executing actions.                                                                 
Excluding []                                                                                                                   
:liquibaseUpdate (Thread[Execution worker for ':' Thread 9,5,main]) completed. Took 0.033 secs.                                                                                                                                                               
                                                                                                                                                                                                                                                              
FAILURE: Build failed with an exception.                                                                                                                                                                                                                      
                                                                                                                               
* What went wrong:                                                                                                             
Execution failed for task ':liquibaseUpdate'.                                                                                  
> The value for task ':liquibaseUpdate' property 'mainClass' is final and cannot be changed any further.                
                                                                                                                                                                                                                                                              
* Try:                                                                                                                                                                                                                                                        
Run with --debug option to get more log output. Run with --scan to get full insights.                                        
                                                                                                                                                                                                                                                              
* Exception is:                                                                                                                                                                                                                                               
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':liquibaseUpdate'.                                                                                                                                                                    
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)                                                                                                                    
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)                                       
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57) 
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
```

### PR DESCRIPTION
**Pull request by bomgar**
closes #70 

I actually have no idea what I'm doing here but it seems to work with 6.3 and 6.4.

### CODE REVIEW

**Comment by stevesaliman** [comment]
This doesn't seem to work fully on my system.  There are no errors, but if I set a mainClassName in my build.gradle file, it doesn't get used.  It is as if Gradle configures all the tasks, then processes the custom extensions, then executes the tasks.  When I was calling setMain at execution time, I got the final value for all of the extension properties.  When I call it in the configure phase, I don't

I'm curious to see if you get the same behavior.  Can you try the following?

1. Add a `System.out.println` to the OutputEnablingLiquibaseRunner.  It doesn't matter what it says, you just want to see proof that the runner was used.
2. Add `mainClassName 'org.liquibase.gradle.OutputEnablingLiquibaseRunner'` to the `liquibase` block of your build.gradle file
3. Try running a liquibase task like `gradlew dropAll`.  Do you see the output from step 1?

**Comment by bomgar** [comment]
You're right it doesn't work. For some reason the mainClassName in the configure method is  `liquibase.integration.commandline.Main` despite the configuration in `build.gradle`

**Comment by stevesaliman** [comment]
I think the issue is that `configure()` runs on once on each task when it is first created, which happens when the plugin is applied, but before Gradle has started processing the liquibase block is processed.  This means we only ever get the default value.  If we want the overridden value, we need to know how the value ended up, which was why I was using it at execution time.

I saw that the Lombok plugin had a similar issue - I wonder if they have a similar bug...

I also saw that there was a related Gradle issue that is now marked as closed.  I'm starting to think that our best bet may be to wait for the next gradle release, though version 6.4.1 which was released after the gradle issue was closed still has the problem.

**Comment by bomgar** [comment]
If I change the configure method like this:
```
	Task configure(Closure closure) {
		conventionMapping("main") {
			project.extensions.findByType(LiquibaseExtension.class).mainClassName
		}
		return super.configure(closure)
	}
```

it actually tries to load the configured main class. But:

```
Successfully started process 'command '/usr/lib/jvm/java-8-openjdk/bin/java''                                                                                              
Error: Could not find or load main class org.liquibase.gradle.OutputEnablingLiquibaseRunner                                                         

```

**Comment by bomgar** [comment]
Ah I was missing the plugin in the `liquibaseRuntime` dependency. This actually seems to work now.

**Comment by bomgar** [comment]
I pushed my changes. @stevesaliman Could you check again?

**Comment by stevesaliman** [comment]
That does indeed seem to work.  I'm a little concerned about relying on an internal API, since they can change without warning, but at least it now works.  The best part is that this won't break backwards compatibility.

Nice find, and thank you for the contribution.

**Pull request merged**
