### PR TITLE
Added @Input annotation on top of def properties to support java 17 l…

### PR DESCRIPTION
**Pull request by Ramanji025**
Added @Input annotation on top of def properties to support java 17 liquibase build

### CODE REVIEW

**Comment by Ramanji025** [comment]
@stevesaliman
Please review and approve the above Pull Request.
I have used latest version this plugin, when i am try to build with Java 17. Since java 17 is strictly uses the groovy props should define @Input or @output or @internal annotations.
Because these annotation are not defined, the build error throws **requiresValue** ... **etc** should be marked with above annotations

**Comment by Ramanji025** [comment]
@PaulJulius @PaulJulius @mariochampion @wwillard7800

**Comment by stevesaliman** [comment]
I'm a little confused about why `@Input` would make a difference here, since it is a Gradle annotation, and I wouldn't expect changing the JDK to change Gradle's behavior - especially on a class that is not a Gradle task, though perhaps having LiquibaseCommand as an `@Input` of a task requires the command's fields to also be annotated...

I'm still trying to reproduce the problem myself, but I'm running into groovy issues.  One thing I want to be careful of is breaking backwards compatibility with older versions of Liquibase, Gradle, Java, etc.

**Comment by MalloD12** [comment]
Hi @Ramanji025,

Can you please share any additional details with us so we can move forward with this change?

Thanks,
Daniel.

**Comment by MalloD12** [comment]
Moving this PR to "In Discussion" column. Please, feel free to provide any details that help us to reproduce this issue and validate this fix, because as mentioned above we couldn't reproduce it. 

Thanks,
Daniel.

**Comment by stevesaliman** [comment]
The LiquibaseCommand class is no longer part of the plugin, as of version 4.0.0, so this PR is no longer needed.

**Pull request closed without merging**
